project:
  type: website

website:
  title: "欢迎来到evan's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
toc: true
format:
  html:
    theme: flatly
    css: styles.css
    html-math-method:
      method: katex
      url: "https://cdn.bootcss.com/KaTeX/0.11.1/"
      # css: "https://cdn.bootcss.com/KaTeX/0.11.1/katex.min.css"

execute:
  freeze: auto


