project:
  type: website

website:
  title: "物理教学"
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer: "© Stack 2024"
  reader-mode: true
  repo-url: https://github.com/yemaobumei
  repo-actions: [edit, issue]  
  navbar:
    right:
      - text: 首页
        href: http://ephys.cn
      - text: 资源下载
        href: http://ephys.cn/download/index/       
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: google
        href: http://google.com/      
toc: true
format:
  html:
    theme: flatly
    css: styles.css
    html-math-method:
      method: katex
      # url: "https://cdn.bootcss.com/KaTeX/0.11.1/"
      # css: "https://cdn.bootcss.com/KaTeX/0.11.1/katex.min.css"
      # 官方网站 cdn太慢直接将js，css，fonts文件下载到本地site_libs/文件更快  https://www.bootcdn.cn/KaTeX/
      url: "/site_libs/katex/"

execute:
  freeze: auto


