project:
  type: website

website:
  title: "欢迎来到evan物理"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    
execute:
  freeze: auto


